from config import getApi
import os
import random

api = getApi()
characters = [
	# Part 1: Phantom Blood
	{'name': 'Jonathan Joestar', 'image': 'jonathan_joestar.png', 'part': 1},
	{'name': 'Dio Brando (Phantom Blood)', 'image': 'dio_brando.png', 'part': 1},
	{'name': 'Robert E. O. Speedwagon', 'image': 'speedwagon.jpg', 'part': 1},
	{'name': 'William A. Zeppeli', 'image': 'william_zeppeli.png', 'part': 1},
	{'name': 'Poco', 'image': 'poco.jpg', 'part': 1},
	{'name': 'Dire', 'image': 'dire.jpg', 'part': 1},
	{'name': 'Straits (Phantom Blood)', 'image': 'straits.png', 'part': 1},
	{'name': 'Tonpetty', 'image': 'tonpetty.png', 'part': 1},
	{'name': 'Erina Pendleton', 'image': 'erina_pendleton.jpg', 'part': 1},
	{'name': 'Wang Chan', 'image': 'wang_chan.jpg', 'part': 1},
	{'name': 'Bruford', 'image': 'bruford.png', 'part': 1},
	{'name': 'Tarkus', 'image': 'tarkus.jpg', 'part': 1},
	{'name': 'Danny', 'image': 'danny.jpg', 'part': 1},
	# Part 2: Battle Tendency
	{'name': 'Joseph Joestar (Battle Tendency)', 'image': 'joseph_joestar.png', 'part': 2},
	{'name': 'Caesar A. Zeppeli', 'image': 'caesar_zeppeli.jpg', 'part': 2},
	{'name': 'Lisa Lisa', 'image': 'lisa_lisa.jpg', 'part': 2},
	{'name': 'Kars (Light Mode)', 'image': 'kars.png', 'part': 2},
	{'name': 'Kars (Ultimate Life Form)', 'image': 'kars_ultimate.jpg', 'part': 2},
	{'name': 'Wamuu', 'image': 'wamuu.png', 'part': 2},
	{'name': 'Esidisi', 'image': 'esidisi.jpg', 'part': 2},
	{'name': 'Santana', 'image': 'santana.jpg', 'part': 2},
	{'name': 'Rudol Von Stroheim', 'image': 'stroheim.jpg', 'part': 2},
	{'name': 'Smokey Brown', 'image': 'smokey.png', 'part': 2},
	{'name': 'Mark', 'image': 'mark.jpg', 'part': 2},
	{'name': 'Messina', 'image': 'messina.png', 'part': 2},
	{'name': 'Loggins', 'image': 'loggins.png', 'part': 2},
	{'name': 'Suzie Q', 'image': 'suzie_q.png', 'part': 2},
	{'name': 'Mario Zeppeli', 'image': 'mario_zeppeli.png', 'part': 2},
	{'name': 'Wired Beck', 'image': 'wired_beck.png', 'part': 2},
	{'name': 'Straits (Battle Tendency)', 'image': 'straits_vampire.png', 'part': 2},
	{'name': 'Donovan', 'image': 'donovan.jpg', 'part': 2},
	# Part 3: Stardust Crusaders
	{'name': 'Jotaro Kujo (Stardust Crusaders)', 'image': 'jotaro_kujo.png', 'part': 3},
	{'name': 'DIO (Stardust Crusaders)', 'image': 'dio_sdc.png', 'part': 3},
	{'name': 'Joseph Joestar (Stardust Crusaders)', 'image': 'joseph_joestar_sdc.jpg', 'part': 3},
	{'name': 'Muhammad Avdol', 'image': 'avdol.png', 'part': 3},
	{'name': 'Noriaki Kakyoin', 'image': 'kakyoin.png', 'part': 3},
	{'name': 'Jean Pierre Polnareff (Stardust Crusaders)', 'image': 'polnareff.jpg', 'part': 3},
	{'name': 'Iggy', 'image': 'iggy.png', 'part': 3},
	{'name': 'Gray Fly', 'image': 'gray_fly.jpg', 'part': 3},
	{'name': 'Captain Tennille (Imposter)', 'image': 'captain_tennille.png', 'part': 3},
	{'name': 'Forever', 'image': 'forever.png', 'part': 3},
	{'name': 'Devo the Cursed', 'image': 'devo.png', 'part': 3},
	{'name': 'Rubber Soul', 'image': 'rubber_soul.jpg', 'part': 3},
	{'name': 'Hol Horse', 'image': 'hol_horse.png', 'part': 3},
	{'name': 'J. Geil', 'image': 'j_geil.jpg', 'part': 3},
	{'name': 'Nena', 'image': 'nena.png', 'part': 3},
	{'name': 'ZZ', 'image': 'zz.png', 'part': 3},
	{'name': 'Enya the Hag', 'image': 'enya.png', 'part': 3},
	{'name': 'Steely Dan', 'image': 'steely_dan.jpg', 'part': 3},
	{'name': 'Arabia Fats', 'image': 'arabia_fats.png', 'part': 3},
	{'name': 'Mannish Boy', 'image': 'mannish_boy.jpg', 'part': 3},
	{'name': 'Cameo', 'image': 'cameo.png', 'part': 3},
	{'name': 'Midler', 'image': 'midler.png', 'part': 3},
	{'name': "N'Doul", 'image': 'ndoul.jpg', 'part': 3},
	{'name': 'Oingo', 'image': 'oingo.jpg', 'part': 3},
	{'name': 'Boingo', 'image': 'boingo.png', 'part': 3},
	{'name': 'Chaka', 'image': 'chaka.png', 'part': 3},
	{'name': 'Khan', 'image': 'khan.png', 'part': 3},
	{'name': 'Mariah', 'image': 'mariah.png', 'part': 3},
	{'name': 'Alessi', 'image': 'alessi.jpg', 'part': 3},
	{'name': "Daniel J. D'Arby", 'image': 'daniel_darby.png', 'part': 3},
	{'name': "Telence T. D'Arby", 'image': 'telence_darby.png', 'part': 3},
	{'name': 'Kenny G.', 'image': 'kenny_g.png', 'part': 3},
	{'name': 'Nukesaku', 'image': 'nukesaku.jpg', 'part': 3},
	{'name': 'Vanilla Ice', 'image': 'vanilla_ice.png', 'part': 3},
	{'name': 'Holy Kujo', 'image': 'holy_kujo.png', 'part': 3},
	{'name': 'Anne', 'image': 'anne.jpg', 'part': 3},
	{'name': 'Roses', 'image': 'roses.png', 'part': 3},
	{'name': 'Pet Shop', 'image': 'pet_shop.jpg', 'part': 3},
	# Diamond is Unbreakable
	{'name': 'Josuke Higashikata', 'image': 'josuke_higashikata.png', 'part': 4},
	{'name': 'Yoshikage Kira', 'image': 'kira.jpg', 'part': 4},
	{'name': 'Yoshikage Kira (Bites the Dust)', 'image': 'kira_btd.png', 'part': 4},
	{'name': 'Koichi Hirose (Act 1)', 'image': 'koichi_hirose_act1.jpg', 'part': 4},
	{'name': 'Koichi Hirose (Act 2)', 'image': 'koichi_hirose_act2.jpg', 'part': 4},
	{'name': 'Koichi Hirose (Act 3)', 'image': 'koichi_hirose_act3.jpg', 'part': 4},
	{'name': 'Okuyasu Nijimura', 'image': 'okuyasu.jpg', 'part': 4},
	{'name': 'Rohan Kishibe', 'image': 'rohan_kishibe.jpg', 'part': 4},
	{'name': 'Jotaro Kujo (Diamond is Unbreakable)', 'image': 'jotaro_kujo_diu.png', 'part': 4},
	{'name': 'Tomoko Higashikata', 'image': 'tomoko.png', 'part': 4},
	{'name': "Nijimura's Father", 'image': 'nijimura.png', 'part': 4},
	{'name': 'Joseph Joestar (Diamond is Unbreakable)', 'image': 'joseph_joestar_diu.png', 'part': 4},
	{'name': 'Reimi Sugimoto', 'image': 'reimi.png', 'part': 4},
	{'name': 'Arnold', 'image': 'arnold.jpg', 'part': 4},
	{'name': 'Shigekiyo Yangu', 'image': 'shigechi.jpg', 'part': 4},
	{'name': 'Mikitaka Hazekura', 'image': 'mikitaka.png', 'part': 4},
	{'name': 'Hayato Kawajiri', 'image': 'hayato.png', 'part': 4},
	{'name': 'Angelo Katagiri', 'image': 'angelo.png', 'part': 4},
	{'name': 'Keicho Nijimura', 'image': 'keicho.jpg', 'part': 4},
	{'name': 'Tamami Kobayashi', 'image': 'tamami.png', 'part': 4},
	{'name': 'Toshikazu Hazamada', 'image': 'hazamada.png', 'part': 4},
	{'name': 'Yukako Yamagishi', 'image': 'yukako.jpg', 'part': 4},
	{'name': 'Akira Otoishi', 'image': 'akira.jpg', 'part': 4},
	{'name': 'Bug-Eaten', 'image': 'bug-eaten.jpg', 'part': 4},
	{'name': 'Yoshihiro Kira', 'image': 'yoshihiro.png', 'part': 4},
	{'name': 'Stray Cat', 'image': 'stray_cat.jpg', 'part': 4},
	{'name': 'Ken Oyanagi', 'image': 'ken.png', 'part': 4},
	{'name': 'Yuya Fungami', 'image': 'yuya.png', 'part': 4},
	{'name': 'Toyohiro Kanedaichi', 'image': 'toyohiro.png', 'part': 4},
	{'name': 'Terunosuke Miyamoto', 'image': 'terunosuke.png', 'part': 4},
	{'name': 'Masazo Kinoto', 'image': 'masazo.png', 'part': 4},
	{'name': 'Tonio Trussardi', 'image': 'tonio.jpg', 'part': 4},
	{'name': 'Aya Tsuji', 'image': 'aya.png', 'part': 4},
	{'name': 'Shizuka Joestar', 'image': 'shizuka.png', 'part': 4},
	{'name': 'Shinobu Kawajiri', 'image': 'shinobu.jpg', 'part': 4},
	{'name': 'Police', 'image': 'police.png', 'part': 4},
	# Golden Wind
	{'name': 'Giorno Giovanna (GE)', 'image': 'giorno_ge.jpg', 'part': 5},
	{'name': 'Giorno Giovanna (GER)', 'image': 'giorno_ger.jpg', 'part': 5},
	{'name': 'Diavolo', 'image': 'diavolo.jpg', 'part': 5},
	{'name': 'Vinegar Doppio', 'image': 'doppio.png', 'part': 5},
	{'name': 'Bruno Bucciarati', 'image': 'bruno.jpg', 'part': 5},
	{'name': 'Leone Abbacchio', 'image': 'abbacchio.png', 'part': 5},
	{'name': 'Guido Mista', 'image': 'mista.jpg', 'part': 5},
	{'name': 'Narancia Ghirga', 'image': 'narancia.jpg', 'part': 5},
	{'name': 'Pannacotta Fugo', 'image': 'fugo.jpg', 'part': 5},
	{'name': 'Trish Una', 'image': 'trish.jpg', 'part': 5},
	{'name': 'Pericolo', 'image': 'pericolo.jpg', 'part': 5},
	{'name': 'Coco Jumbo', 'image': 'coco_jumbo.png', 'part': 5},
	{'name': 'Mario Zucchero', 'image': 'zucchero.jpg', 'part': 5},
	{'name': 'Sale', 'image': 'sale.jpg', 'part': 5},
	{'name': 'Leaky-Eye Luca', 'image': 'luca.png', 'part': 5},
	{'name': 'Risotto Nero', 'image': 'risotto.jpg', 'part': 5},
	{'name': 'Formaggio', 'image': 'formaggio.jpg', 'part': 5},
	{'name': 'Illuso', 'image': 'illuso.png', 'part': 5},
	{'name': 'Prosciutto', 'image': 'prosciutto.jpg', 'part': 5},
	{'name': 'Pesci', 'image': 'pesci.png', 'part': 5},
	{'name': 'Melone', 'image': 'melone.png', 'part': 5},
	{'name': 'Ghiaccio', 'image': 'ghiaccio.jpg', 'part': 5},
	{'name': 'Sorbet', 'image': 'sorbet.png', 'part': 5},
	{'name': 'Gelato', 'image': 'gelato.jpg', 'part': 5},
	{'name': 'Squalo', 'image': 'squalo.jpg', 'part': 5},
	{'name': 'Tiziano', 'image': 'tiziano.jpg', 'part': 5},
	{'name': 'Carne', 'image': 'carne.jpg', 'part': 5},
	{'name': 'Cioccolata', 'image': 'cioccolata.jpg', 'part': 5},
	{'name': 'Secco', 'image': 'secco.jpg', 'part': 5},
	{'name': 'Jean Pierre Polnareff (Golden Wind)', 'image': 'polnareff_gw.jpg', 'part': 5},
	{'name': 'Scolippi', 'image': 'scolippi.jpg', 'part': 5},
	# Stone Ocean
	{'name': 'Jolyne Cujoh', 'image': 'jolyne.jpg', 'part': 6},
	{'name': 'Enrico Pucci (White Snake)', 'image': 'pucci.png', 'part': 6},
	{'name': 'Enrico Pucci (C-Moon)', 'image': 'pucci_cmoon.JPG', 'part': 6},
	{'name': 'Enrico Pucci (MiH)', 'image': 'pucci_mih.JPG', 'part': 6},
	{'name': 'Ermes Costello', 'image': 'ermes.png', 'part': 6},
	{'name': 'Emporio Alnino', 'image': 'emporio.png', 'part': 6},
	{'name': 'Weather Emporio', 'image': 'weather_emporio.png', 'part': 6},
	{'name': 'Jotaro Kujo (Sone Ocean)', 'image': 'jotaro_kujo_so.jpg', 'part': 6},
	{'name': 'Foo Fighters', 'image': 'foo_fighters.png', 'part': 6},
	{'name': 'Narciso Anasui', 'image': 'anasui.jpg', 'part': 6},
	{'name': 'Weather Report', 'image': 'weather_report.png', 'part': 6},
	{'name': 'Gwess', 'image': 'gwess.png', 'part': 6},
	{'name': 'Donatello Versus', 'image': 'donatello.png', 'part': 6},
	{'name': 'Rikiel', 'image': 'rikiel.png', 'part': 6},
	{'name': 'Ungalo', 'image': 'ungalo.png', 'part': 6},
	{'name': 'The Green Baby', 'image': 'green_baby.JPG', 'part': 6},
	{'name': 'Johngalli A', 'image': 'johngalli.png', 'part': 6},
	{'name': 'Sports Maxx', 'image': 'sports_maxx.jpg', 'part': 6},
	{'name': 'Miuccia Miuller', 'image': 'miuccia.png', 'part': 6},
	{'name': 'Thunder McQueen', 'image': 'thunder_mcqueen.png', 'part': 6},
	{'name': 'Miraschon', 'image': 'miraschon.png', 'part': 6},
	{'name': 'Lang Rangler', 'image': 'lang_rangler.png', 'part': 6},
	{'name': 'Viviano Westwood', 'image': 'viviano.png', 'part': 6},
	{'name': 'Kenzou', 'image': 'kenzou.png', 'part': 6},
	{'name': 'Guccio', 'image': 'guccio.png', 'part': 6},
	{'name': 'D an G', 'image': 'd_an_g.png', 'part': 6},
	{'name': 'Romeo Jisso', 'image': 'romeo.png', 'part': 6},
	{'name': 'Perla Pucci', 'image': 'perla_pucci.png', 'part': 6},
	{'name': 'Gloria Costello', 'image': 'gloria_costello.png', 'part': 6},
]

def postStatus(update):
	status = api.PostUpdate(update)
	print(status)

def postMatchUp(text, image1, image2):
	api.PostUpdate(text, media=[image1, image2])

def createMatchUp():
	first_character = random.randint(0, len(characters) - 1)
	second_character = random.randint(0, len(characters) - 1)
	while first_character == second_character:
		second_character = random.randint(0, len(characters) - 1)
	post_text = characters[first_character]['name'] + ' VS ' + characters[second_character]['name']
	if characters[first_character]['part'] > 5 or characters[second_character]['part'] > 5:
		post_text = post_text + ' #JoJoVSManga'
	status = postMatchUp(post_text, 'characters/' + characters[first_character]['image'], 'characters/' + characters[second_character]['image'])

createMatchUp()